language: node_js
node_js:
   - "0.10"
env:
  global:
    - secure: "JH7N4LAjAywkt010l+20n3FWsrzX2bjzvm+wKf04+IIoNp6QTkYqRFTT6uII\n1Fqs2x0H5cyPgum/ji++vdFLOKkusKTTUdqDr3a8296wdIxm3VpXCusjHqkP\nnpL5SYGuUPyAfIT5YOstO7kfk11Nuex9bWb1mmF/JcBI7P+AbLI="
    - secure: "Q9rDQLDcsiZvooElo4ztdx7q90B10me5h1kqg/NxjGf52B3M4ruwzX/nk5rm\nUAVPE1pyTt+O/yDoz5uamsTxzMP8wDg4NKZFkPlPBBsWMcjn6dS3h0Tt39md\nAsLp4fDPdS4SfsI8DmydOKyRhrms7KyWtDme9GA3zqoG+77+Xw8="
    - MAJOR_VERSION: 0
    - MINOR_VERSION: 3
    - REVISION: 1

before_script:
    - export VERSION="${MAJOR_VERSION}.${MINOR_VERSION}.${REVISION}.${TRAVIS_BUILD_NUMBER}"
    - export JS_TEST_DRIVER="${HOME}/temp_tools/JsTestDriver-1.3.3d.jar"
    - export NUGET="${HOME}/temp_tools/NuGet.exe"
    - export TEMP_TOOLS="${HOME}/temp_tools"
    - npm install -g typescript
    - npm install -g jake
    - npm install jade
    - npm install fs-extra
    - npm install js-yaml
    - npm install optimist
    - npm -g install closurecompiler
    - mkdir "${HOME}/temp_tools"
    - sudo apt-get install mono-complete
    - mozroots --import --sync
    - "curl -o ${HOME}/temp_tools/JsTestDriver-1.3.3d.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.3d.jar'"
    - curl -o ${HOME}/temp_tools/NuGet.exe -L 'https://www.nuget.org/nuget.exe'
    - "java -jar ${HOME}/temp_tools/JsTestDriver-1.3.3d.jar --port 9876 &"
    - "sleep 3"
    - "phantomjs scripts/phantomjs-jstd.js &"
    - "sleep 3"

script:
    - mkdir out
    - jake -f .build.js buildAndPublish --trace
    - "mkdir ${HOME}/build_artifacts"
    - "cp -R out/* ${HOME}/build_artifacts"
    - "git config --global user.email 'guryanovev@gmail.com'"
    - "git config --global user.name 'Travis'"
    - "git remote add upstream https://${GH_TOKEN}@github.com/guryanovev/JohnSmith.git"
    - "git checkout --orphan gh-pages"
    - "rm -r *"
    - "git rm -rf ."
    - "cp -R ${HOME}/build_artifacts/* ."
    - "git add -f ."
    - git commit -q -m "Travis build $TRAVIS_BUILD_NUMBER pushed to gh-pages"
    - "git push -fq upstream gh-pages"
